[package]
name = "spacewire-rs"
version = "0.1.0"
edition = "2021"
authors = ["Andrés MANELLI <am@toroid.io>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
